title = "Airspace for Hugo"
baseURL = "https://ewanesergio.netlify.com/"
languageCode = "fr-ca"
DefaultContentLanguage = "fr"
title = "Ewane Sergio"
theme = "airspace-hugo"
googleAnalytics = "UA-111222298-1"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[menu]

  [[menu.header]]
    weight = 2
    name = "Travail"
    url = "/work"
  [[menu.header]]
    weight = 3
    name = "Blog"
    url = "/blog"
  [[menu.header]]
    weight = 4
    name = "Compétences"
    url = "/service"
  [[menu.header]]
    weight = 5
    name = "Contact"
    url = "/contact"

  [[menu.footer]]
    weight = 1
    name = "À propos de nous"
    url = "#"
  [[menu.footer]]
    weight = 2
    name = "Contactez nous"
    url = "#"
  [[menu.footer]]
    weight = 3
    name = "Comment ça marche"
    url = "#"
  [[menu.footer]]
    weight = 4
    name = "Blog"
    url = "#"
  [[menu.footer]]
    weight = 5
    name = "Termes"
    url = "#"

# The site's parameters
[params]

  # If you want to remove the copyright text you need a Themefisher license.
  # This license is offered with a 50% discount for all Hugo users.
  # For information see https://github.com/gohugoio/hugoThemes/issues/260

  dateFormat = "6 January 2006"

  home = "Acceuil"

  [params.slider]
    enable = true
    title = "SERGIO, EWANE EBOUELE"
    subtitle = "Msc. Statistique"
    

  [params.wrapper]
    enable = true
    title = "À propos de nous"
    italic = "Je suis un habitué de la statistique. Je cumule actuellement plus de 10 ans de scolarité et d'expérience professionnel dans le domaine de la statistique."
    paragraph = "De manière plus détaillé, J'ai fait 6 ans de formation à l'ISSEA de Yaoundé (Cameroun) pour obtenir les diplômes de technicien supérieur et d'ingénieur des travaux de la statistique. Deux ans après l'obtention de ces diplômes, J'ai obtenu une maîtrise en statistique à l'université Laval."

  [params.blog]
    enable = true
    title = "Derniers travaux réalisés"
    subtitle = "Mettez vous à jour avec nous, tout le temps et partout !"

  [params.feature]
    enable = true
    title = "Mes convictions."
    content = "Ma compétence n'est pas incontournable dans la vie. Sans moi on peut faire. Mais, avec moi se sera mieux fait !"
    [params.feature.button]
      caption = "Voir mes travaux"
      url = "#"

  [params.call]
    enable = true
    title = "Avec les chiffres on fait plus !"
    paragraph = "Sans les nombres, tu ne prouves rien. Avec eux, tu peux te tromper. Avec leur maitrise, tu peux rendre la vue à un aveugle du monde des affaires !"

  [params.contact]
    enable = true
    title = "Envoie nous un message"
    subtitle = "Donnez nous votre avis sur nos derniers travaux !"
    [params.contact.form]
      name = "Ton nom"
      email = "Ton email"
      subject = "Sujet"
      message = "Ton message"
      button = "Envoi message"
    [params.contact.box]
      title = "Arrêt pour une visite"
      address = "Université Laval, Québec, Canada"
      email = "Email: sergio.ewane-ebouele.1@ulaval.ca"
      phone = "Phone: +1 581 578 9352"
    [params.contact.gmaps]
      title = "Localise moi sur Google Maps"
